wazuh/wazuh-kubernetes

cleanup.md

Hello team, 
This PR solves the issue #10.
We have added the file cleanup.md whit the steps to clean up the environment. 
Regards,

Clean up documentation

---

CHANGELOG.md
elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-conf.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-0-conf.yaml
wazuh_managers/wazuh-worker-0-sts.yaml
wazuh_managers/wazuh-worker-1-conf.yaml
wazuh_managers/wazuh-worker-1-sts.yaml

Hello team, 
This PR meets one of the requirements of Issue #22.
We have also removed a deprecated section from the Wazuh cluster. 
Best regards,

Upgrade Wazuh version 3.8.0

---

elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-sts.yaml

Hello  team,
This PR updates pro-cloud branch to v3.8.0.
We have installed an agent and checked that the versions installed in the trial are correct.
Best regards,

Update wazuh version

---

CHANGELOG.md
elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-0-sts.yaml
wazuh_managers/wazuh-worker-1-sts.yaml

Hello team,
This PR updates Wazuh to version 3.8.1.
Best regards,

Update to Wazuh version 3.8.1

---

CHANGELOG.md
elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-0-sts.yaml
wazuh_managers/wazuh-worker-1-sts.yaml

Hello team,
This PR updates Wazuh version to 3.8.1.
Best regards,

Update pro cloud Wazuh version to 3.8.1

---

CHANGELOG.md
elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-0-sts.yaml
wazuh_managers/wazuh-worker-1-sts.yaml

Hello team,
This PR updates Wazuh version to 3.8.2.
Kind regards,

Update to Wazuh version 3.8.2

---

instructions.md

Hello team,
This PR solves issue #33.
Best regards,

Fix broken links of instructions.md

---

CHANGELOG.md
elastic_stack/kibana/kibana-deploy.yaml
elastic_stack/kibana/nginx-deploy.yaml
elastic_stack/logstash/logstash-deploy.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-0-sts.yaml
wazuh_managers/wazuh-worker-1-sts.yaml

Hello team!
This PR updates Wazuh to 3.9.0 version.
Regards!

Update to Wazuh version 3.9.0

---

README.md

Add reference to local-env branch on the readme

---

minikube/base.yaml
minikube/elastic/elasticsearch-sts.yaml
minikube/kibana/kibana-deploy.yaml
minikube/kibana/nginx-deploy.yaml
minikube/wazuh/wazuh-sts.yaml

This PR updates the local environment branch for minikube deployments.

Bump minikube branch

---

secrets/wazuh-api-cred-secret.yaml
secrets/wazuh-authd-pass-secret.yaml
secrets/wazuh-cluster-key-secret.yaml

fix for https://github.com/wazuh/wazuh-kubernetes/issues/114

add missing namespaces for secrets

---

elastic_stack/elasticsearch/cluster/elasticsearch-data-sts.yaml
elastic_stack/elasticsearch/cluster/elasticsearch-master-sts.yaml
elastic_stack/elasticsearch/single-node/elasticsearch-sts.yaml
wazuh_managers/wazuh-master-sts.yaml
wazuh_managers/wazuh-worker-sts.yaml

fix related to https://github.com/wazuh/wazuh-kubernetes/issues/112

add fix chroot error

---

README.md
wazuh_managers/wazuh_conf/master.conf
wazuh_managers/wazuh_conf/worker.conf

This PR updates the repo content in the README and removes a deprecated config block from the config and adds the current format.

Fix manager deprecation warnings

---

base/aws-gp2-storage-class.yaml

Force same AZ for cloud volumes

---

certs/odfe_cluster/generate_certs.sh
instructions.md

This PR closes #130
- include self signed gen. script
- document certs requirements on `installation.md`

Document certs generation script

---

instructions.md

This PR fixes a typo on kibana selector described in `installation.md`

Fix kibana selector on sample code

---

cleanup.md

This PR improves wording and simplifies the `cleanup` docs.

Improve cleanup docs

---

wazuh/elastic_stack/elasticsearch/cluster/elasticsearch-sts.yaml

This PR closes #145 
- Set DISABLE_INSTALL_DEMO_CONFIG to prevent demo config script from running

Set DISABLE_INSTALL_DEMO_CONFIG

---

local-environment.md

This PR will fix several small details on the local-env docs. Also will sync with the latest changes from the official docs.

Fix instructions

---

instructions.md

This PR fixes #89 
- Update docs to state Elasticsearch cluster support

Update legacy docs

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR updates osse.conf for the upcoming release 4.1

Update ossec.conf for Wazuh 4.1

---

upgrade.md
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Rename ossec.conf to manager.conf

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

Closes #177 
This PR update the last parameters introduced in 4.3.0 auth section inside ossec.conf.

Changed Authd deprecated options

---

wazuh/elastic_stack/elasticsearch/cluster/elasticsearch-sts.yaml

Log4j fix added

---

wazuh/indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml

This PR is related to https://github.com/wazuh/wazuh-packages/issues/1469

Remove plugin from opensearch.yml

---

wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/wazuh-packages/issues/1470

Disable multitenancy

---

README.md

This PR corrects the tree format in the README.

Correct tree format

---

wazuh/secrets/dashboard-cred-secret.yaml

Dashboard secret password updated

---

README.md
envs/eks/dashboard-resources.yaml
envs/eks/indexer-resources.yaml
envs/eks/kustomization.yml
envs/eks/storage-class.yaml
envs/eks/wazuh-master-resources.yaml
envs/eks/wazuh-worker-resources.yaml
envs/local-env/indexer-resources.yaml
envs/local-env/kustomization.yml
envs/local-env/storage-class.yaml
envs/local-env/wazuh-resources.yaml
wazuh/base/storage-class.yaml
wazuh/base/wazuh-ns.yaml
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-dashboard/dashboard-svc.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-api-svc.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/indexer_stack/wazuh-indexer/indexer-svc.yaml
wazuh/kustomization.yml
wazuh/secrets/indexer-cred-secret.yaml
wazuh/secrets/wazuh-api-cred-secret.yaml
wazuh/secrets/wazuh-authd-pass-secret.yaml
wazuh/secrets/wazuh-cluster-key-secret.yaml
wazuh/wazuh_managers/wazuh-cluster-svc.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-master-svc.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml
wazuh/wazuh_managers/wazuh-workers-svc.yaml

This PR aims to update copyright format

Changed copyright format:

---

wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

This PR fixes the mount path of the PV assigned to Wazuh indexer

PV mount path modification

---

wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

This PR Fixes java_opts variable into Wazuh indexer manifest

Fix java_opts variable

---

CHANGELOG.md

This PR merges `4.4` into `4.5`.
Related: https://github.com/wazuh/wazuh/issues/17281

Merge `4.4` into `4.5`

---

CHANGELOG.md
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR merges `4.5` into `master`.
Related: https://github.com/wazuh/wazuh/issues/17281

Merge `4.5` into `master`

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR delete update_from_year parameter for Wazuh install
Closes https://github.com/wazuh/wazuh-kubernetes/issues/412

Delete update_from_year parameter

---

CHANGELOG.md
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR is related to: https://github.com/wazuh/wazuh-kubernetes/issues/424

Merge `4.5` into `4.5.1`

---

CHANGELOG.md

This PR is related to: https://github.com/wazuh/wazuh-kubernetes/issues/453

Merge `4.5.3` into `4.6.0`

---

CHANGELOG.md
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR is related to: https://github.com/wazuh/wazuh-kubernetes/issues/453

Merge `4.6.0` into `4.7.0`

---

CHANGELOG.md
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR is related to: https://github.com/wazuh/wazuh-kubernetes/issues/453

Merge `4.7.0` into `master`

---

CHANGELOG.md
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

Merge 4.7.0 into 4.7.1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/internal-devel-requests/issues/394.

Dashboard default route update

---

wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/499
The aim of this PR is to bump the 4.8.0 branch into the master branch.

Merge 4.8.0 into master

---

wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

Related Issue: https://github.com/wazuh/wazuh-kubernetes/issues/512

[ISM rollover] Run indexer-ism-init.sh script

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-kubernetes/issues/529
The aim of this PR is to bump the changes of the 4.8.1 branch to the master branch

Merge 4.8.1 into master

---

CHANGELOG.md

https://github.com/wazuh/wazuh-kubernetes/issues/545
The aim of this PR is to bump the changes of the 4.8.0 branch to the 4.8.1 branch

Merge 4.8.0 into 4.8.1

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

Close https://github.com/wazuh/wazuh-kubernetes/issues/540
The goal of this PR is to update the vulnerability detector configuration

Updated Vulnerability detection

---

wazuh/certs/indexer_cluster/generate_certs.sh
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR modifies the URL for access to Wazuh indexer from the other services.
Issue related https://github.com/wazuh/wazuh-kubernetes/issues/581

Use LB service for access Wazuh indexer

---

wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml

Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/592

Rollback ISM changes

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

Related: https://github.com/wazuh/wazuh-kubernetes/issues/630

Merge 4.8.1 into 4.8.2

---

wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

Related: https://github.com/wazuh/wazuh-kubernetes/issues/630

Merge 4.8.2 into 4.9.0

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue related https://github.com/wazuh/wazuh-kubernetes/issues/645

Rename docker image for beta6

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue related https://github.com/wazuh/wazuh-kubernetes/issues/645

Rename docker image for 4.8.0

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/649

Reverted tag for 4.7.4 RC1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue related https://github.com/wazuh/wazuh-kubernetes/issues/654

Rollback image version

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/667

Change image tag for rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/667

Rollback image tag

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/673

Commit image tag to rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/680

Commit rc1 image version

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Change docker image tag

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert docker image tag

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/689

Commit image version rc3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/689

Rollback image version rc3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/693

Commit image version rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/693

Rollback image version rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/707

Changed image tag for 4.8.0-rc4

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/724

Changed image tag for 4.9.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/724

Reverted tag from 4.9.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/735

Reverted image tag for 4.8.1 RC1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/739

Change image version por rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/748

Changed image tag for `4.9.0-alpha2`

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/748

Reverted image tag for `4.9.0-alpha2`

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.8.1 RC3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.8.1 RC3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.8.1-RC4

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.8.1 RC4

---

wazuh/wazuh_managers/wazuh_conf/worker.conf

Merge 4.9.0 into master

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.9.0 Alpha3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.9.0 Alpha3

---

wazuh/wazuh_managers/wazuh_conf/worker.conf

Merge 4.9.0 into 4.10.0

---

wazuh/wazuh_managers/wazuh_conf/worker.conf

Reverts wazuh/wazuh-kubernetes#764

Revert "Revert "Merge branch '4.9.0' into merge-4.9.0-into-master""

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

related: https://github.com/wazuh/wazuh-kubernetes/issues/779

Changed image tag for 4.9.0 Beta 1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

related: https://github.com/wazuh/wazuh-kubernetes/issues/779

Revert image tag for 4.9.0 Beta 1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.9.0 beta2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.9.0 beta2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue related https://github.com/wazuh/wazuh-kubernetes/issues/789

Revert image tag

---

CHANGELOG.md

Merge 4.9.1 into 4.10.0

---

CHANGELOG.md

Merge 4.10.0 into master

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.9.0-RC1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.9.0-RC1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.9.0-rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.9.0-rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/821

Change image tag for 4.9.1-RC1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/821

reverted image tag for 4.9.1-rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Changed image tag for 4.10.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Reverted image tag for 4.10.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Change docker image tag for 4.9.1-rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert docker image tag for 4.9.1-rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Change docker image tag for 4.9.1-RC3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert docker image tag for 4.9.1-RC3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/849

Changed image tag for  4.10.0-alpha2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/849

Revert image tag for  4.10.0-alpha2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/853

Change image tag for 4.9.1-rc4

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/853

Revert image tag for 4.9.1-rc4

---

CHANGELOG.md

This PR is related to the issue: https://github.com/wazuh/wazuh-kubernetes/issues/858

Merge 4.10.1 into 4.10.2

---

CHANGELOG.md
SECURITY.md

This PR is related to the issue: https://github.com/wazuh/wazuh-kubernetes/issues/858

Merge 4.10.2 into master

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/863

Change image tag for 4.10.0-alpha2 

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/863

Revert image tag for 4.10.0-alpha2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

This PR is related to https://github.com/wazuh/wazuh-kubernetes/issues/873.

Images tag changed for 4.9.2-rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

This PR is related to https://github.com/wazuh/wazuh-kubernetes/issues/873.

Revert tags to 4.9.2

---

.github/workflows/deployment-test.yml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/878

Change secret name

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/891

changed image tag for 4.10.0-alpha3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/891

Revert image tag for 4.10.0-alpha3

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/897

Changed image tag for 4.10.0-beta1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/897

Revert image tag for v4.10.0-beta1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/908

Changed image tag for 4.10.0-rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/908

Revert image tag for 4.10.0-rc1

---

CHANGELOG.md

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/913

Adding new changelog format

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/918

Changed image tag for 4.10.0-rc2

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/934

Revert image tag for 4.10.0-rc3

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-kubernetes/issues/939

Merge 4.11.0 into 4.12.0

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/944

Change image tag for v4.10.1-rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/962

Change image tag for v4.11.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/962

Revert image tag for v4.11.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue
https://github.com/wazuh/wazuh-kubernetes/issues/975

Bump remove back 4.11.0 beta1

---

README.md

This PR updates the references of the branch `master` to `main` 
- #972

Update references of 'master' branch to 'main'

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

close https://github.com/wazuh/wazuh-kubernetes/issues/982

Reverted rc1 tag from 4.11.0

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/1004

Bump 4.13.0 version

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Update image tag to v4.12.0-alpha1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert update image tag to v4.12.0-alpha1

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Bump to 4.12.1

---

VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue: https://github.com/wazuh/wazuh-kubernetes/issues/1041

Bump stage rc1 for 4.12.0

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue: https://github.com/wazuh/wazuh-kubernetes/issues/1041

Revert image tag for 4.12.0-rc1

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Bump to 4.12.2

---

.github/workflows/deployment-test.yml
CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Bump to 6.0.0

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

This issue aims to bump main to 5.0.0 version
- #1054

Bump to 5.0.0

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/1057

Revert docker image tag for 4.10.2-rc1

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/1061

Bump 4.14.0 version

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-kubernetes/issues/1071

Delete 4.12.2 references

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-kubernetes/issues/1071

delete 4.12.2 section from changelog

---

CHANGELOG.md

Related: https://github.com/wazuh/wazuh-kubernetes/issues/1071

Delete changelog 4.12.2 section from main branch

---

VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Bump revision for 4.12.1 rc1 and change docker images tag

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert docker images tag for 4.12.1-rc1

---

VERSION.json

Issue: https://github.com/wazuh/wazuh-kubernetes/issues/1079

Bump test/1079-integrate-bumper-script-via-github-action branch

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Bump version to 4.13.1 in the 4.13.1 branch

---

.github/workflows/4_bumper_repository.yml

Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/1116

Merge 4.13.1 into 4.14.0

---

VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/2625

Bump test/554-test branch

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related: https://github.com/wazuh/wazuh-kubernetes/issues/1134

Revert image tag for v4.13.0-rc1

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/1138

Revert rc2 stage into 4.13.0 branch

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3035

Bump 4.14.1 branch

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related issue https://github.com/wazuh/wazuh-kubernetes/issues/1155

Merge 4.13.0 into 4.13.1

---

VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3471

Bump 4.13.0 branch

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/1168

Revert images tags

---

CHANGELOG.md
wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

Related Issue https://github.com/wazuh/wazuh-kubernetes/issues/1171

Add opensearch_dashboard.yml parameters

---

wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Revert image tag for 4.13.0 RC4

---

CHANGELOG.md
wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml

This PR is related to https://github.com/wazuh/internal-devel-requests/issues/3056.

Dashboard settings added

---

CHANGELOG.md
VERSION.json
wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml
wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
wazuh/wazuh_managers/wazuh-master-sts.yaml
wazuh/wazuh_managers/wazuh-worker-sts.yaml

Issue: https://github.com/wazuh/wazuh-qa-automation/issues/3910

Bump 4.13.1 branch

---

.gitignore
CHANGELOG.md
wazuh/wazuh_managers/wazuh-master-svc.yaml
wazuh/wazuh_managers/wazuh_conf/master.conf
wazuh/wazuh_managers/wazuh_conf/worker.conf

This PR is related to https://github.com/wazuh/wazuh-kubernetes/issues/1190.

Merge 4.13.0 into 4.14.0
