wazuh/wazuh-kubernetes

README.md, elastic_stack/elasticsearch/cluster/elasticsearch-data-sts.yaml, elastic_stack/elasticsearch/cluster/elasticsearch-master-sts.yaml, elastic_stack/elasticsearch/single-node/elasticsearch-sts.yaml, elastic_stack/kibana/kibana-deploy.yaml, elastic_stack/kibana/nginx-deploy.yaml, elastic_stack/logstash/logstash-deploy.yaml, wazuh_managers/wazuh-master-sts.yaml, wazuh_managers/wazuh-worker-0-sts.yaml, wazuh_managers/wazuh-worker-1-sts.yaml
Hello team,
We have updated the version of the images used to create the pods to 3.7.2_6.5.4 version.
Additionally, we have added the directory structure to the README.md file to maintain consistency with the other repositories. 
Kind regards,
=> Update wazuh images to 3.7.2 6.5.4

base/aws-gp2-storage-class.yaml
Hello team,
Due to the impossibility of communicating STS pods with volumes located in different availability zones (AZs) we have established the deployment of workers nodes in zone b.
This problem is solved in Kubernetes version 1.12. When EKS supports this version, this alternative solution will not be necessary. 
Best regards,
=> Availability Zone us-east-2b

CHANGELOG.md, elastic_stack/elasticsearch/cluster/elasticsearch-data-sts.yaml, elastic_stack/elasticsearch/cluster/elasticsearch-master-sts.yaml, elastic_stack/elasticsearch/single-node/elasticsearch-sts.yaml, instructions.md, upgrade.md
Hello team,
This PR solves #39 , now `Wazuh elasticsearch` images are used instead of images from `Elastic`.
Also, the documents were updated to the latest versions.
Regards
=> Added Wazuh elasticsearch images

elastic_stack/kibana/kibana-deploy.yaml
Hello team,
This PR closes #97 by increasing the value of `max-old-space-size` in the Kibana service deploy file.
Regards,
Daniel Folch
=> Increase Kibana max-old-space-size

minikube/elastic/elasticsearch-sts.yaml, minikube/kibana/kibana-deploy.yaml, minikube/kibana/nginx-deploy.yaml, minikube/wazuh/wazuh-sts.yaml
This PR bumps local-env branch to latest version 3.13.1_7.8.0 and fixes resource limits on the Kibana service, incresing max-old-space-size to 2048.
=> Bump local-environment and fix resource limits

secrets/wazuh-api-cred-secret.yaml, secrets/wazuh-authd-pass-secret.yaml, secrets/wazuh-cluster-key-secret.yaml, wazuh_managers/wazuh-master-conf.yaml, wazuh_managers/wazuh-master-sts.yaml, wazuh_managers/wazuh-worker-conf.yaml, wazuh_managers/wazuh-worker-sts.yaml
Using Kubernetes secrets for storing various credentials (Issue: #29)
- Added `Secret` object for each credential
- Mounted Wazuh authd password in master pod
- Storing all other keys as environment variables
- Replacing cluster key placeholder in docker entrypoint script (https://github.com/wazuh/wazuh-docker/pull/393)
=> Using Kubernetes secrets to store credentials

wazuh_managers/wazuh_conf/master.conf, wazuh_managers/wazuh_conf/worker.conf
This PR closes #129 and #134
- Update references to deprecated `ossec-` prefix in favor of `wazuh-` prefix
=> Adopt Wazuh standard on tool names

wazuh_managers/wazuh_conf/master.conf, wazuh_managers/wazuh_conf/worker.conf
This PR fixes #133 
- Refer to master manager using relative DNS instead of FQDN
=> Use relative DNS name for master manager

wazuh/certs/odfe_cluster/generate_certs.sh
The DN of the the generated admin cert does not match what's configured in [elasticsearch.yml](https://github.com/wazuh/wazuh-kubernetes/blob/381a08e569bf2acfd2ce1bc5a619021eb80bc0b2/wazuh/elastic_stack/elasticsearch/elastic_conf/elasticsearch.yml#L21), which causes an error if you try and run `securityadmin.sh`.
=> Change admin cert DN to match config in elasticsearch.yml

envs/local-env/indexer-resources.yaml
This PR increase the memory resources assigned to the Wazuh indexer container because it was throwing OOM errors.
=> Local environment resources update

wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml
This issue is related to #189 and #220. Default indexer memory limit is not enough and an OOM error is raised.
=> Indexer container memory limit increased

README.md, wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml, wazuh/kustomization.yml
This PR closes #248 
This was tested using Docker 4.3.0 images generated with branch [640-kibana_user_parameter](https://github.com/wazuh/wazuh-docker/tree/640-kibana_user_parameter). 
Procedure description:
1. Deploy Wazuh using kubernetes repository.
2. Modify the `kibanaserver` hash in `internal_users.yml` configmap.
3. Modify the base64 `dashboard-cred` `password`.
4. Redeploy Wazuh using kubernetes repository.
5. Delete Dashboard pod.
6. Access Wazuh dashboard using a browser.
=> dashboard-cred secrect added

upgrade.md
Closes #222 
This PR updates the [upgrade.md](https://github.com/wazuh/wazuh-kubernetes/blob/master/upgrade.md) file to remove the reference to `queue/agent-groups`. I have also updated the other paths according to what exists [here](https://github.com/wazuh/wazuh-docker/blob/750fe5ffe82b2eaf78f8a1e2f9581c48f368e081/wazuh-odfe/config/permanent_data.env#L3-L12):
``` 
PERMANENT_DATA[((i++))]="/var/ossec/api/configuration"
PERMANENT_DATA[((i++))]="/var/ossec/etc"
PERMANENT_DATA[((i++))]="/var/ossec/logs"
PERMANENT_DATA[((i++))]="/var/ossec/queue"
PERMANENT_DATA[((i++))]="/var/ossec/agentless"
PERMANENT_DATA[((i++))]="/var/ossec/var/multigroups"
PERMANENT_DATA[((i++))]="/var/ossec/integrations"
PERMANENT_DATA[((i++))]="/var/ossec/active-response/bin" …
```
=> Remove `queue/agent-groups` from upgrade.md

wazuh/wazuh_managers/wazuh-master-sts.yaml, wazuh/wazuh_managers/wazuh-worker-sts.yaml
Hi Wazuh Contributors, 
Post K8S deployment on EKS, my agents could not synchronize newly created groups(agent.conf).
My deployment is based on branch: v4.3.3 
After examining the logs on master and worker nodes I've noticed the following err msg:
`Jun 21, 2022 @ 11:36:20.000 wazuh-remoted ERROR  Cannot create multigroup directory 'var/multigroups/2ce0beec': Permission denied (13)`
Steps to reproduce:
- Deploy branch v4.3.3
- Install at least one agent on target machine
- Create a new group via Wazuh Dashboard (UI)
- Assign the group to newly created agent (I've used [agent_groups](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-groups.html#agent-groups) cli)
- Agent won't be synchronized
In order to fix the issue, I've sshed to the containers and changed the …
=> fix permission issue for /var/ossec/var/multigroups

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
This PR updated the `firewall-drop` command configuration according to the documentation:
- https://documentation.wazuh.com/current/user-manual/capabilities/active-response/ar-use-cases/blocking-attacks.html
We noticed this thanks to a community in slack.
=> Firewall-drop command config update

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
This PR fixes the `firewall-drop` script name in branch `4.4`.
=> Firewall drop script name update (4.4)

README.md
Closes: https://github.com/wazuh/wazuh-kubernetes/issues/414
The aim of this PR is to remove the duplicated "branches" paragraph in the `README.md` file of the repository.
=> Deleted duplicated branches paragraph in `README.md`

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
This PR adds the corresponding AlmaLinux entry in the vulnerability detector default configuration after the changes in [Add support for AlmaLinux in Vulnerability Detector](https://github.com/wazuh/wazuh/pull/16343#top)
#16343.
=> Updating vulnerability detector default configuration with AlmaLinux support

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
|Related issue|
|---|
|wazuh/wazuh#18516|
This PR adds the corresponding Debian Bookworm entry in the vulnerability detector default configuration after the changes in [Add support for Debian Bookworm in Vulnerability Detector](https://github.com/wazuh/wazuh/pull/18516)
=> Add Debian Bookworm to VDT default configuration

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
|Related issue|
|---|
|wazuh/wazuh#17617|
This PR adds the corresponding Amazon Linux 2023 entry in the vulnerability detector default configuration after the changes in [Add support for Amazon Linux 2023 in Vulnerability Detector](https://github.com/wazuh/wazuh/issues/17617)
=> Add Amazon Linux 2023 VDT default configuration

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
Related: https://github.com/wazuh/wazuh-kubernetes/issues/573
The aim of this PR is to adapt the Kubernetes deployment to the new changes of the VD and indexer configuration.  The changes consist in removing the hardcoding of the indexer username password in the `ossec.conf` of the master and workers nodes.
The rest of the changes are done in the Wazuh docker repository: https://github.com/wazuh/wazuh-docker/pull/1196
=> VD keystore changes

wazuh/wazuh_managers/wazuh_conf/master.conf, wazuh/wazuh_managers/wazuh_conf/worker.conf
This PR deletes configuration about`/var/log/syslog` and `/var/log/dpkg.log` into `ossec.conf` file.
Related Issue https://github.com/wazuh/wazuh/issues/22511
=> Delete syslog and dpkg log configuration

wazuh/wazuh_managers/wazuh_conf/worker.conf
This reverts commit 56c64a6fc8b0615fcb3b27a6e55e70582e01c8ea, reversing changes made to eedc893da191899d4bdeca021db1d0d0b967db2d. (PR: https://github.com/wazuh/wazuh-kubernetes/pull/763)
Related: #761
=> Revert "Merge branch '4.9.0' into merge-4.9.0-into-master"

CHANGELOG.md, wazuh/wazuh_managers/wazuh-worker-sts.yaml
This PR adds a labelSelector into podAffinity statement for a warning generated during deployment.
Related issue https://github.com/wazuh/wazuh-kubernetes/issues/868
=> Add labelSelector 

.github/workflows/deployment-test.yml
This PR adds a new workflow in wazuh-kubernetes repository to make a new workflow for test PRs.
Related issue https://github.com/wazuh/wazuh-kubernetes/issues/878
=> Add PR test workflow for Kubernetes

.gitignore, CHANGELOG.md, tools/repository_bumper.sh
close https://github.com/wazuh/wazuh-kubernetes/issues/1034
A script is developed to bump the version and revision of the wazuh-kubernetes repository. This script handles different conditions and adapts to all repositories in the xdrsiem DevOps team.
- bump of patch version, example: 4.13.0 to 4.13.1
- bump of minor version, example: 4.13.0 to 4.14.0
- bump of mayor version, example: 4.13.0 to 5.0.0
- bump of revision, example: alpha0 to beta1
- bump of minor version, example 4.13 to 4.14
- bump of 4.x version, example: 4.x to 5.x
- 4.13.0 to 4.14.0: https://github.com/wazuh/wazuh-kubernetes/issues/1034#issuecomment-2825214176
- 4.14.0 to 4.14.1: https://github.com/wazuh/wazuh-kubernetes/issues/1034#issuecomment-2825223114
- 4.14.1 to 5.0.0: …
=> Added repository_bumper script
